- hosts: localhost
  gather_facts: false
  tasks:
    - assert:
        that: "{{ program_path is defined }}"
        fail_msg: need program path

    - name: Initialize stack
      set_fact:
        stack: []

    - name: Load program
      set_fact:
        program: '{{ lookup("file", program_path) }}'

    - name: Parse program
      include_role:
        name: parse

    - debug:
        var: cst

    - name: Extract AST
      include_role:
        name: extract-ast

    - debug:
        var: ast

    - include_vars: call/builtins/vars.yml

    - name: Set up context
      set_fact:
        env: # Current environment, initially empty
          parent:
          bindings: {}
        expr: "{{ ast }}"

    - name: Start evaluation
      include_tasks: eval.yml

    - debug:
        msg: "Final result is: {{ result }}"
