- import_tasks: lex_whitespace.yml

- assert:
    that: '{{ program[program_idx | int] == "(" }}'
    fail_msg: 'Expected "("'

- include_tasks: parse.yml

- assert:
    that: '{{ program_idx | int >= program | length }}'
    fail_msg: 'Expected EOF'
