- name: Lex whitespace
  set_fact:
    program_idx: '{{ program_idx | int + (program[program_idx | int:] | regex_search("^\s*") | length) }}'

- name: Parse token
  set_fact:
    cst: "{{ cst + [token] }}"
    program_idx: "{{ program_idx | int + (token | length) }}"
  when: token
  vars:
    token: '{{ program[program_idx | int:] | regex_search("^[^\s\)]+") }}'

- name: Lex whitespace
  set_fact:
    program_idx: '{{ program_idx | int + (program[program_idx | int:] | regex_search("^\s*") | length) }}'

- name: Parse next
  include_tasks: parse.yml
  when: program[program_idx | int] != ')'
