- set_fact:
    cst:
      - define
      - '{{ name }}'
      - "{{ ['lambda', parameters] + body }}"
  vars:
    name: '{{ cst[1][0] }}'
    parameters: '{{ cst[1][1:] }}'
    body: '{{ cst[2:] }}'

