- set_fact:
    stack: "{{ stack + [ast_children] }}"
    ast_children: []

- include_tasks: parse_children.yml
  loop: "{{ cst[2:] }}"
  loop_control:
    loop_var: cst_child

- set_fact:
    ast:
      type: LAMBDA
      parameters: "{{ cst[1] }}"
      body:
        type: BODY
        children: "{{ ast_children }}"
    stack: "{{ stack[:-1] }}"
    ast_children: "{{ stack[-1] }}"
