- set_fact:
    stack: "{{ stack + [cst] }}"
    cst: "{{ cst_child }}"

- name: Parse child
  include_tasks: parse.yml

- set_fact:
    ast_children: "{{ ast_children + [ast] }}"
    stack: "{{ stack[:-1] }}"
    cst: "{{ stack[-1] }}"
