- include_tasks: desugar_define_function.yml
  when:
    - cst[1] is iterable
    - cst[1] is not string

- set_fact:
    stack: "{{ stack + [cst] }}"
    cst: "{{ cst[2] }}"

- include_tasks: parse.yml

- set_fact:
    stack: "{{ stack[:-1] }}"
    cst: "{{ stack[-1] }}"
    ast:
      type: DEFINE
      name: "{{ stack[-1][1] }}"
      expr: "{{ ast }}"
