- set_fact:
    stack: "{{ stack + [ast_children] }}"
    ast_children: []

- include_tasks: parse_children.yml
  loop: "{{ cst }}"
  loop_control:
    loop_var: cst_child

- set_fact:
    ast:
      type: CALL
      target: "{{ ast_children[0] }}"
      arguments: "{{ ast_children[1:] }}"
    stack: "{{ stack[:-1] }}"
    ast_children: "{{ stack[-1] }}"
