- debug: var=cst

- name: dispatch to parser
  include_tasks: "parse_{{ parse_type | trim }}.yml"
  vars:
    parse_type: >-
      {% if cst | int or cst == "0" %}
      int
      {% elif cst is string %}
      name
      {% elif cst is iterable %}
      sexpr
      {% else %}
      invalid
      {% endif %}
